name: Run BTC Alert Bot

on:
  schedule:
    - cron: "*/5 * * * *" # Roda a cada 5 minutos

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar o bot
        run: node btcAlertMeBot.js
